[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[window]
dimensions = { columns = 80, lines = 26 }

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"


[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
chars = "docker compose pull && docker compose down && docker compose up -d --build --force-recreate --remove-orphans && docker compose logs -f"

[[keyboard.bindings]]
key = "M"
mods = "Control|Shift"
chars = """\
select opt in update_reboot bench.sh docker_install sysbeanch exit; do \
case $opt in \
update_reboot) apt update && apt upgrade -y && reboot;; \
bench.sh) wget -qO- bench.sh | bash ;;\
docker_install) curl -fsSL https://get.docker.com | sh ;;\
sysbeanch) apt install sysbench -y && clear && sysbench cpu --cpu-max-prime=20000 --threads=1 run ;;\
exit) break;; \
esac; \
break; \
done
"""

